(function() {var implementors = {
"trillium_api":[["impl&lt;T: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"trillium_api/struct.Body.html\" title=\"struct trillium_api::Body\">Body</a>&lt;T&gt;"],["impl&lt;T: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"trillium_api/struct.Json.html\" title=\"struct trillium_api::Json\">Json</a>&lt;T&gt;"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"trillium_api/struct.Halt.html\" title=\"struct trillium_api::Halt\">Halt</a>"],["impl&lt;T: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"trillium_api/struct.State.html\" title=\"struct trillium_api::State\">State</a>&lt;T&gt;"]],
"trillium_async_std":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"trillium_async_std/struct.ClientConfig.html\" title=\"struct trillium_async_std::ClientConfig\">ClientConfig</a>"]],
"trillium_caching_headers":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"trillium_caching_headers/struct.Etag.html\" title=\"struct trillium_caching_headers::Etag\">Etag</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"trillium_caching_headers/struct.Modified.html\" title=\"struct trillium_caching_headers::Modified\">Modified</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"trillium_caching_headers/struct.CachingHeaders.html\" title=\"struct trillium_caching_headers::CachingHeaders\">CachingHeaders</a>"]],
"trillium_channels":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"trillium_channels/enum.Version.html\" title=\"enum trillium_channels::Version\">Version</a>"]],
"trillium_compression":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"trillium_compression/enum.CompressionAlgorithm.html\" title=\"enum trillium_compression::CompressionAlgorithm\">CompressionAlgorithm</a>"]],
"trillium_cookies":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"trillium_cookies/struct.CookiesHandler.html\" title=\"struct trillium_cookies::CookiesHandler\">CookiesHandler</a>"]],
"trillium_head":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"trillium_head/struct.Head.html\" title=\"struct trillium_head::Head\">Head</a>"]],
"trillium_http":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"trillium_http/enum.Version.html\" title=\"enum trillium_http::Version\">Version</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"trillium_http/enum.Method.html\" title=\"enum trillium_http::Method\">Method</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"trillium_http/enum.KnownHeaderName.html\" title=\"enum trillium_http::KnownHeaderName\">KnownHeaderName</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"trillium_http/enum.Status.html\" title=\"enum trillium_http::Status\">Status</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"trillium_http/struct.HttpConfig.html\" title=\"struct trillium_http::HttpConfig\">HttpConfig</a>"]],
"trillium_logger":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"trillium_logger/enum.Target.html\" title=\"enum trillium_logger::Target\">Target</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"trillium_logger/enum.ColorMode.html\" title=\"enum trillium_logger::ColorMode\">ColorMode</a>"]],
"trillium_proxy":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"trillium_proxy/upstream/struct.ForwardProxy.html\" title=\"struct trillium_proxy::upstream::ForwardProxy\">ForwardProxy</a>"]],
"trillium_redirect":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"trillium_redirect/enum.RedirectStatus.html\" title=\"enum trillium_redirect::RedirectStatus\">RedirectStatus</a>"]],
"trillium_smol":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"trillium_smol/struct.ClientConfig.html\" title=\"struct trillium_smol::ClientConfig\">ClientConfig</a>"]],
"trillium_static_compiled":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"trillium_static_compiled/struct.StaticCompiledHandler.html\" title=\"struct trillium_static_compiled::StaticCompiledHandler\">StaticCompiledHandler</a>"]],
"trillium_testing":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"trillium_testing/struct.RuntimelessClientConfig.html\" title=\"struct trillium_testing::RuntimelessClientConfig\">RuntimelessClientConfig</a>"]],
"trillium_tokio":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"trillium_tokio/struct.ClientConfig.html\" title=\"struct trillium_tokio::ClientConfig\">ClientConfig</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()