[package]
name = "trillium-forwarding"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"
description = "handler for trillium.rs that rewrites host/scheme from forwarded/x-forwarded headers"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trillium-rs/trillium"
readme = "../README.md"
keywords = ["trillium", "framework", "async"]
categories = ["web-programming::http-server", "web-programming"]

[dependencies]
cidr = "0.1.1"
log = "0.4.14"
trillium = { path = "../trillium", version = "^0.1.0" }

[dev-dependencies]
trillium-logger = { path = "../logger" }
trillium-smol = { path = "../smol" }
trillium-testing = { path = "../testing" }
