comment_width = 100
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "One"
imports_granularity = "Crate"
normalize_comments = true
reorder_impl_items = true
unstable_features = true
use_field_init_shorthand = true
version = "Two"
wrap_comments = true
