(function() {var implementors = {
"trillium":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"trillium/struct.Info.html\" title=\"struct trillium::Info\">Info</a>"]],
"trillium_api":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"trillium_api/enum.Error.html\" title=\"enum trillium_api::Error\">Error</a>"]],
"trillium_aws_lambda_example":[["impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"trillium_aws_lambda_example/struct.HelloTemplate.html\" title=\"struct trillium_aws_lambda_example::HelloTemplate\">HelloTemplate</a>&lt;'a&gt;"]],
"trillium_caching_headers":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"trillium_caching_headers/struct.CacheControlHeader.html\" title=\"struct trillium_caching_headers::CacheControlHeader\">CacheControlHeader</a>"]],
"trillium_client":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"trillium_client/struct.UnexpectedStatusError.html\" title=\"struct trillium_client::UnexpectedStatusError\">UnexpectedStatusError</a>"]],
"trillium_compression":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"trillium_compression/enum.CompressionAlgorithm.html\" title=\"enum trillium_compression::CompressionAlgorithm\">CompressionAlgorithm</a>"]],
"trillium_example":[["impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"trillium_example/struct.HelloTemplate.html\" title=\"struct trillium_example::HelloTemplate\">HelloTemplate</a>&lt;'a&gt;"]],
"trillium_forwarding":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"trillium_forwarding/struct.Forwarded.html\" title=\"struct trillium_forwarding::Forwarded\">Forwarded</a>&lt;'_&gt;"]],
"trillium_http":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"trillium_http/enum.Version.html\" title=\"enum trillium_http::Version\">Version</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"trillium_http/struct.HeaderName.html\" title=\"struct trillium_http::HeaderName\">HeaderName</a>&lt;'_&gt;"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"trillium_http/enum.Error.html\" title=\"enum trillium_http::Error\">Error</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"trillium_http/enum.Status.html\" title=\"enum trillium_http::Status\">Status</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"trillium_http/struct.HeaderValue.html\" title=\"struct trillium_http::HeaderValue\">HeaderValue</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"trillium_http/struct.Headers.html\" title=\"struct trillium_http::Headers\">Headers</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"trillium_http/enum.KnownHeaderName.html\" title=\"enum trillium_http::KnownHeaderName\">KnownHeaderName</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"trillium_http/enum.Method.html\" title=\"enum trillium_http::Method\">Method</a>"]],
"trillium_websockets":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"trillium_websockets/enum.Error.html\" title=\"enum trillium_websockets::Error\">Error</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()