[package]
name = "trillium-aws-lambda-example"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2021"
publish = false
description = "example application using aws lambda"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trillium-rs/trillium"
readme = "../README.md"
keywords = ["trillium", "framework", "async"]
categories = ["web-programming::http-server", "web-programming"]

[dependencies]
trillium-aws-lambda = { path = "../aws-lambda" }
lamedh_runtime = "0.3.0"
serde_json = "1.0.94"
env_logger = "0.10.0"
trillium = { path = "../trillium" }
trillium-router = { path = "../router" }
trillium-logger = { path = "../logger" }
trillium-cookies = { path = "../cookies" }
trillium-sessions = { path = "../sessions" }
trillium-askama = { path = "../askama" }
futures-lite = "1.12.0"
askama = "0.12.0"
async-session-cookie-store = { git = "https://github.com/http-rs/async-session", branch = "overhaul-session-and-session-store" }
