[package]
name = "trillium-html-rewriter"
version = "0.0.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[dependencies]
trillium = { path = "../trillium" }
futures-lite = "1.11.3"
async-global-executor = "2.0.2"
lol-async = "0.1.1"

[dev-dependencies]
trillium-smol-server = { path = "../smol-server" }
trillium-proxy = { path = "../proxy" }
env_logger = "0.8.3"
