name: docs

on:
  push:
    branches:
      - main
jobs:
  docs:
    name: build rustdocs and put them on github pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy
        override: true

    - name: Build Documentation
      run: >-
        RUSTDOCFLAGS="-Z unstable-options --enable-index-page"
        cargo +nightly doc
        --no-deps
        --all
        --features smol,trillium-testing/smol

    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@364c31d33bb99327c77b3a5438a83a357a6729ad
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: rustdocs
        publish_dir: ./target/doc
        force_orphan: true
